format: 0.0.1-prealpha.1
stages:
  ipfs_deploy:
    package: ipfs
    uri: fs/./build
  from_deploy:
    package: local-dev-ens
    depends_on: ipfs_deploy
    config:
      domainName: test1.eth
      ports:
        ethereum: 8545
  from_deploy2:
    package: local-dev-ens
    depends_on: ipfs_deploy
    config:
      domainName: test2.eth
      ports:
        ethereum: 8545
  from_uri:
    package: local-dev-ens
    uri: ipfs/QmVdDR6QtigTt38Xwpj2Ki73X1AyZn5WRCreBCJq1CEtpF
    config:
      domainName: test3.eth
      ports:
        ethereum: 8545
