[package]
name = "query"
version = "0.1.0"
description = "Query module of Ethereum polywrapper"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[dependencies]
thiserror = "1.0.30"
getrandom = { version = "*", features = ["custom"] }
polywrap-wasm-rs = { path = "../../../../wasm/rs" }
serde = { version = "1.0", features = ["derive"] }
ethers-core = { version = "0.6.0", features = [] }
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
num-traits = "0.2.14"
regex = "1"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'