[package]
name = "query"
version = "0.1.0"
description = "Query module of IDNA-UTS46 polywrapper"
authors = [
  "Nestor Amesty <nestor@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[dependencies]
#polywrap-wasm-rs = { version = "0.0.1-prealpha-dev.37.4", path = "../../../../wasm/rs" }
serde = { version = "1.0", features = ["derive"] }
idna = "0.2.3"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'