name: simple-storage
jobs:
  cases:
    steps:
    - uri: fs/build
      method: deployContract
      input:
    jobs:
      case1:
        steps:
        - uri: fs/build
          method: setData
          input:
            address: "$cases.0.data"
            value: 100
        - uri: fs/build
          method: getData
          input:
            address: "$cases.0.data"
